config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  ActiveAdmin.routes(self)
  devise_for :users

  resources :compagny do
    namespace :account do
      root to: "boards#index"
        resources :flows, only: [:index, :show, :new, :create, :edit, :update]
        resources :organizations, only: [:index, :show, :create, :edit, :update ] do
          resources :persons, only: [:index, :show, :create, :edit, :update ]
        end
        resources :persons, only: [:index]
        resources :users, only: [:index, :new, :create, :edit, :update]
      end
    end


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%select_compagny_user%>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Copernic</a>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <%if @choisecompagny != nil %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=@choisecompagny.find(params[:compagny_id]).name%> <span class="caret"></span></a>

            <ul class="dropdown-menu">

               <% @choisecompagny.each do |t|  %>
               <li><%= link_to compagny_account_root_path(t.id) do %>
                  <%= t.name %></li>
                  <%if t.id == @choisecompagny.last.id %>
                  <%else%>
                    <li role="separator" class="divider"></li>
                   <%end%>
                  <%end%>

                  <%end%>
            </ul>
          </li>
        </ul>
        <%end%>
      <%end%>

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%if user_signed_in? %>
          <%if @choisecompagny != nil %>


          <% if current_user.admin %>


            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contacts <span class="caret"></span></a>
              <ul class="dropdown-menu">
                 <li><%= link_to  compagny_account_organizations_path(params[:compagny_id])  do %>
                     <%= t ".sign_out", default: "List Organizations" %>
                  <% end %>
                  <li><%= link_to  compagny_account_persons_path(params[:compagny_id])  do %>
                    <%= t ".sign_out", default: "List Persons" %>
                  <% end %>
              </ul>
            </li>

          <%end%>



            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Flows <span class="caret"></span></a>
              <ul class="dropdown-menu">
                 <li><%= link_to  compagny_account_flows_path(params[:compagny_id])  do %>
                     <%= t ".sign_out", default: "List Flows" %>
                  <% end %>
                  <li><%= link_to  new_compagny_account_flow_path(params[:compagny_id])  do %>
                    <%= t ".sign_out", default: "New Flow" %>
                  <% end %>
              </ul>
            </li>

          <%end%>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
             <li><%= link_to edit_user_registration_path  do %>
                 <%= t ".sign_out", default: "Preference" %>
              <% end %>
              <% if current_user.manager %>

                <li><%= link_to compagny_account_users_path(params[:compagny_id])  do %>
                   <%= t ".sign_out", default: "Users" %>
                <% end %>
              <% end %>

            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to destroy_user_session_path, method: :get do %>
                 <%= t ".sign_out", default: "Log out" %>
              <% end %>
          </ul>
        </li>
        <%else%>
          <li><%= link_to("Login", new_user_session_path)%></li>
        <%end%>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>